// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLW4G6rFJfjuhFyWGWLbh9ac2JHhDxhzY',
    appId: '1:844675301835:web:9d3e622d15459f346fb64e',
    messagingSenderId: '844675301835',
    projectId: 'web-scraping-price-tracker',
    authDomain: 'web-scraping-price-tracker.firebaseapp.com',
    storageBucket: 'web-scraping-price-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSgHfDg-NHP3Ei39DuS1PcqyC8-bJ6e4',
    appId: '1:844675301835:android:2857a72ac7b862356fb64e',
    messagingSenderId: '844675301835',
    projectId: 'web-scraping-price-tracker',
    storageBucket: 'web-scraping-price-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW3zkoVggnZ16hqNj4iZVgsd6H6fMc1gs',
    appId: '1:844675301835:ios:2fd778e719db9aae6fb64e',
    messagingSenderId: '844675301835',
    projectId: 'web-scraping-price-tracker',
    storageBucket: 'web-scraping-price-tracker.firebasestorage.app',
    iosBundleId: 'com.example.webScraperPriceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW3zkoVggnZ16hqNj4iZVgsd6H6fMc1gs',
    appId: '1:844675301835:ios:2fd778e719db9aae6fb64e',
    messagingSenderId: '844675301835',
    projectId: 'web-scraping-price-tracker',
    storageBucket: 'web-scraping-price-tracker.firebasestorage.app',
    iosBundleId: 'com.example.webScraperPriceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLW4G6rFJfjuhFyWGWLbh9ac2JHhDxhzY',
    appId: '1:844675301835:web:7247d2277c30b2656fb64e',
    messagingSenderId: '844675301835',
    projectId: 'web-scraping-price-tracker',
    authDomain: 'web-scraping-price-tracker.firebaseapp.com',
    storageBucket: 'web-scraping-price-tracker.firebasestorage.app',
  );
}
